server:
    port: 8585

spring:
    autoconfigure:
       exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    session:
       store-type: redis
       redis:
          flush-mode: IMMEDIATE
    redis:
       host: redis-17294.c93.us-east-1-3.ec2.cloud.redislabs.com
       jedis:
          pool:
             max-idle: 8
             max-total: 16
             min-idle: 4
       port: 17294
       password: jTg6lvzKF0LTvbeTUUewJWaaVrgoWNZ8
    rabbitmq:
       host: localhost
       port: "5672"
       username: eventoapp
       password: segredo
    listener:
       default-requeue-rejected: "false"
       retry:
             enabled: "true"
             max-attempts: "3"
             initial-interval: "5000"
                         
name:
    topicexchange:
       eventoapp: eventoapp.integration.exchange
    routingKey:
       eventoapp: routingKey_eventoapp
        
eventows:
    endpoint:
       uri: http://localhost:9090/eventoWS

