server:
    port: 8585
    
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    session:
        store-type: redis
        redis:
            flush-mode: IMMEDIATE
    redis:
        host: redis-17294.c93.us-east-1-3.ec2.cloud.redislabs.com
        jedis:
            pool:
                max-idle: 8
                max-total: 16
                min-idle: 4
        port: 17294
        password: jTg6lvzKF0LTvbeTUUewJWaaVrgoWNZ8
    
eventows:
    endpoint:
        uri: http://localhost:9090/eventoWS

