server:
    port: 8585
    servlet:
      context-path: /
      session:
        cookie:
          path: /

spring:
    jmx:
       enabled: false
    autoconfigure:
       exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    session:
       store-type: redis
       redis:
          flush-mode: IMMEDIATE
    redis:
       #host: redis-17294.c93.us-east-1-3.ec2.cloud.redislabs.com
       host: ${REDIS_HOST}
       jedis:
          pool:
             max-idle: 8
             max-total: 16
             min-idle: 4
       #port: 17294
       port: ${REDIS_PORT}
       #password: jTg6lvzKF0LTvbeTUUewJWaaVrgoWNZ8
       password: ${REDIS_PASSWORD}
    rabbitmq:
       #host: localhost
       host: ${RABBITMQ_HOST}
       #port: 5672
       port: ${RABBITMQ_PORT}
       #username: eventoapp
       username: ${RABBITMQ_USERNAME}
       #password: segredo
       password: ${RABBITMQ_PASSWORD}
    listener:
       default-requeue-rejected: false
       retry:
             enabled: true
             max-attempts: 3
             initial-interval: 5000
                         
name:
    topicexchange:
       #eventoapp: eventoapp.integration.exchange
       eventoapp: ${RESPONSE_EXCHANGE}
    routingKey:
       #eventoapp: routingKey_eventoapp
       eventoapp: ${RESPONSE_ROUTING_KEY}
        
eventows:
    endpoint:
       #uri: http://localhost:9090/eventoWS
       uri: ${EVENTO_WS_URI}/eventoWS

